---
- name: list containers on hosts
  hosts: all
  become: yes
  tasks:
    - name: get info on docker host and list containers matching the filter
      docker_host_info:
        containers: yes
      register: result

    - name: Print return information from the previous task
      debug:
        msg: "{{ item }}"
      with_items: "{{ result.containers | map(attribute='Names') | list }}"